version: '3'

services:

  web:
    build: ./web
    restart: always
    environment:
      - APACHE_RUN_USER=#1000
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    ports:
      - ${APACHE2_PORT}:80
    working_dir: ${APP_PATH_CONTAINER}

  db:
    image: mysql
    restart: always
    volumes:
      - ${DB_PATH_HOST}:${DB_PATH_CONTAINER}
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=api_db
    ports:
      - ${MYSQL_PORT}:3306
    command: --default-authentication-plugin=mysql_native_password


  composer:
    image: composer:1.6
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}
    command: composer install

  

    